AWSTemplateFormatVersion: '2010-09-09'

Description: LaunchTemplate Creation for EKS Managed Nodegroup

Mappings:
  ServicePrincipals:
    aws-cn:
      ec2: ec2.amazonaws.com.cn
    aws:
      ec2: ec2.amazonaws.com

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: Node parameters
        Parameters:
          - NodeInstanceType
          - NodeVolumeSize
          - KeyName
          - KubeletExtraArguments
      - Label:
          default: Multus parameters
          Parameters:
          - MultusSubnetsAz
          - MultusSecurityGroupIds
        
Parameters:
  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: The EC2 Key Pair to allow SSH access to the instances
  NodeInstanceType:
    Type: String
    Default: c5.large
    AllowedValues:
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.12xlarge
      - c5.18xlarge
      - c5.24xlarge
      - c5.metal
      - c5d.large
      - c5d.xlarge
      - c5d.2xlarge
      - c5d.4xlarge
      - c5d.9xlarge
      - c5d.18xlarge
      - c5n.large
      - c5n.xlarge
      - c5n.2xlarge
      - c5n.4xlarge
      - c5n.9xlarge
      - c5n.18xlarge
      - c6i.large
      - c6i.xlarge
      - c6i.2xlarge
      - c6i.4xlarge
      - c6i.8xlarge
      - c6i.12xlarge
      - c6i.16xlarge
      - c6i.24xlarge
      - c6i.32xlarge
      - c6i.metal
      - c6in.large
      - c6in.xlarge
      - c6in.2xlarge
      - c6in.4xlarge
      - c6in.8xlarge
      - c6in.12xlarge
      - c6in.16xlarge
      - c6in.24xlarge
      - c6in.32xlarge
      - c6in.metal
      - c6g.medium
      - c6g.large
      - c6g.xlarge
      - c6g.2xlarge
      - c6g.4xlarge
      - c6g.8xlarge
      - c6g.12xlarge
      - c6g.16xlarge
      - c6gn.metal
      - c6gn.medium
      - c6gn.large
      - c6gn.xlarge
      - c6gn.2xlarge
      - c6gn.4xlarge
      - c6gn.8xlarge
      - c6gn.12xlarge
      - c6gn.16xlarge
      - c7g.medium
      - c7g.large
      - c7g.xlarge
      - c7g.2xlarge
      - c7g.4xlarge
      - c7g.8xlarge
      - c7g.12xlarge
      - c7g.16xlarge
      - c7gn.metal
      - c7gn.medium
      - c7gn.large
      - c7gn.xlarge
      - c7gn.2xlarge
      - c7gn.4xlarge
      - c7gn.8xlarge
      - c7gn.12xlarge
      - c7gn.16xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - m5.metal
      - m5a.large
      - m5a.xlarge
      - m5a.2xlarge
      - m5a.4xlarge
      - m5a.8xlarge
      - m5a.12xlarge
      - m5a.16xlarge
      - m5a.24xlarge
      - m5ad.large
      - m5ad.xlarge
      - m5ad.2xlarge
      - m5ad.4xlarge
      - m5ad.12xlarge
      - m5ad.24xlarge
      - m5d.large
      - m5d.xlarge
      - m5d.2xlarge
      - m5d.4xlarge
      - m5d.8xlarge
      - m5d.12xlarge
      - m5d.16xlarge
      - m5d.24xlarge
      - m5d.metal
      - m5dn.large
      - m5dn.xlarge
      - m5dn.2xlarge
      - m5dn.4xlarge
      - m5dn.8xlarge
      - m5dn.12xlarge
      - m5dn.16xlarge
      - m5dn.24xlarge
      - m5n.large
      - m5n.xlarge
      - m5n.2xlarge
      - m5n.4xlarge
      - m5n.8xlarge
      - m5n.12xlarge
      - m5n.16xlarge
      - m5n.24xlarge
      - m6i.large
      - m6i.xlarge
      - m6i.2xlarge
      - m6i.4xlarge
      - m6i.8xlarge
      - m6i.12xlarge
      - m6i.16xlarge
      - m6i.24xlarge
      - m6i.32xlarge
      - m6i.metal
      - m6in.large
      - m6in.xlarge
      - m6in.2xlarge
      - m6in.4xlarge
      - m6in.8xlarge
      - m6in.12xlarge
      - m6in.16xlarge
      - m6in.24xlarge
      - m6in.32xlarge
      - m6in.metal
      - m6i.large
      - m6i.xlarge
      - m6i.2xlarge
      - m6i.4xlarge
      - m6i.8xlarge
      - m6i.12xlarge
      - m6i.16xlarge
      - m6i.24xlarge
      - m6i.32xlarge
      - m6i.metal
      - m6in.large
      - m6in.xlarge
      - m6in.2xlarge
      - m6in.4xlarge
      - m6in.8xlarge
      - m6in.12xlarge
      - m6in.16xlarge
      - m6in.24xlarge
      - m6in.32xlarge
      - m6in.metal
      - m6g.medium
      - m6g.large
      - m6g.xlarge
      - m6g.2xlarge
      - m6g.4xlarge
      - m6g.8xlarge
      - m6g.12xlarge
      - m6g.16xlarge
      - m6gn.metal
      - m6gn.medium
      - m6gn.large
      - m6gn.xlarge
      - m6gn.2xlarge
      - m6gn.4xlarge
      - m6gn.8xlarge
      - m6gn.12xlarge
      - m6gn.16xlarge
      - m7g.medium
      - m7g.large
      - m7g.xlarge
      - m7g.2xlarge
      - m7g.4xlarge
      - m7g.8xlarge
      - m7g.12xlarge
      - m7g.16xlarge
      - m7gn.metal
      - m7gn.medium
      - m7gn.large
      - m7gn.xlarge
      - m7gn.2xlarge
      - m7gn.4xlarge
      - m7gn.8xlarge
      - m7gn.12xlarge
      - m7gn.16xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - r5.12xlarge
      - r5.16xlarge
      - r5.24xlarge
      - r5.metal
      - r5a.large
      - r5a.xlarge
      - r5a.2xlarge
      - r5a.4xlarge
      - r5a.8xlarge
      - r5a.12xlarge
      - r5a.16xlarge
      - r5a.24xlarge
      - r5ad.large
      - r5ad.xlarge
      - r5ad.2xlarge
      - r5ad.4xlarge
      - r5ad.12xlarge
      - r5ad.24xlarge
      - r5d.large
      - r5d.xlarge
      - r5d.2xlarge
      - r5d.4xlarge
      - r5d.8xlarge
      - r5d.12xlarge
      - r5d.16xlarge
      - r5d.24xlarge
      - r5d.metal
      - r5dn.large
      - r5dn.xlarge
      - r5dn.2xlarge
      - r5dn.4xlarge
      - r5dn.8xlarge
      - r5dn.12xlarge
      - r5dn.16xlarge
      - r5dn.24xlarge
      - r5n.large
      - r5n.xlarge
      - r5n.2xlarge
      - r5n.4xlarge
      - r5n.8xlarge
      - r5n.12xlarge
      - r5n.16xlarge
      - r5n.24xlarge
      - r6i.large
      - r6i.xlarge
      - r6i.2xlarge
      - r6i.4xlarge
      - r6i.8xlarge
      - r6i.12xlarge
      - r6i.16xlarge
      - r6i.24xlarge
      - r6i.32xlarge
      - r6i.metal
      - r6in.large
      - r6in.xlarge
      - r6in.2xlarge
      - r6in.4xlarge
      - r6in.8xlarge
      - r6in.12xlarge
      - r6in.16xlarge
      - r6in.24xlarge
      - r6in.32xlarge
      - r6in.metal
      - r6i.large
      - r6i.xlarge
      - r6i.2xlarge
      - r6i.4xlarge
      - r6i.8xlarge
      - r6i.12xlarge
      - r6i.16xlarge
      - r6i.24xlarge
      - r6i.32xlarge
      - r6i.metal
      - r6in.large
      - r6in.xlarge
      - r6in.2xlarge
      - r6in.4xlarge
      - r6in.8xlarge
      - r6in.12xlarge
      - r6in.16xlarge
      - r6in.24xlarge
      - r6in.32xlarge
      - r6in.metal
      - r6g.medium
      - r6g.large
      - r6g.xlarge
      - r6g.2xlarge
      - r6g.4xlarge
      - r6g.8xlarge
      - r6g.12xlarge
      - r6g.16xlarge
      - r6gn.metal
      - r6gn.medium
      - r6gn.large
      - r6gn.xlarge
      - r6gn.2xlarge
      - r6gn.4xlarge
      - r6gn.8xlarge
      - r6gn.12xlarge
      - r6gn.16xlarge
      - r7g.medium
      - r7g.large
      - r7g.xlarge
      - r7g.2xlarge
      - r7g.4xlarge
      - r7g.8xlarge
      - r7g.12xlarge
      - r7g.16xlarge
      - r7gn.metal
      - r7gn.medium
      - r7gn.large
      - r7gn.xlarge
      - r7gn.2xlarge
      - r7gn.4xlarge
      - r7gn.8xlarge
      - r7gn.12xlarge
      - r7gn.16xlarge
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - t3a.nano
      - t3a.micro
      - t3a.small
      - t3a.medium
      - t3a.large
      - t3a.xlarge
      - t3a.2xlarge
    ConstraintDescription: Must be a valid EC2 instance type
    Description: EC2 instance type for the node instances
  NodeVolumeSize:
    Type: Number
    Default: 20
    Description: "Node volume size."
    Description: "Tag on EKS managed node to trigger Lambda action for Multus interface attachment."
  KubeletExtraArguments:
    Type: String
    Default:  "--node-labels=is_worker=true --cpu-manager-policy=static"
    Description: "Arguments to pass to the kubelet bootstrap script."
  MultusSubnets:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: The List of Multus subnets from where multus 2ndary ENI will be connected to.
  MultusSecurityGroupIds:
    Type: "List<AWS::EC2::SecurityGroup::Id>"
    Description: The security groups of the Multus Network Interfaces. Along with the order of security group selection, each will be assigned to each MultusSubnet in above list. If number of security group doesn't match with number of multus subnets, then the 1st security group will be used for all multus subnets.
  
Resources:
  EksMngLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "EksMngLt-${AWS::StackName}"
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              DeleteOnTermination: true
              VolumeSize: !Ref NodeVolumeSize
              VolumeType: gp2
        InstanceType: !Ref NodeInstanceType
        KeyName: !Ref KeyName        
        UserData:
          Fn::Base64: !Sub |
            Content-Type: multipart/mixed; boundary="==BOUNDARY=="
            MIME-Version: 1.0

            --==BOUNDARY==
            Content-Type: text/x-shellscript; charset="us-ascii"
            #!/bin/bash
            set -o xtrace
            # List your multus subnets and Security Group
            subnetids="${SubnetIds}"
            secgrpids="${SecGrpIds}"
            IFS=' ' read -ra subnetList <<< "$subnetids"
            IFS=' ' read -ra secGrpList <<< "$secgrpids"
            subnetListLen=${!#subnetList[@]}
            secGrpListLen=${!#secGrpList[@]}
            
            # If just one security group is defined, then use it for every subnet
            if [ $subnetListLen != $secGrpListLen ]; then
                x=0
                for subnet in "${!subnetList[@]}";
                do
                    secGrpList[${!x}]="${!secGrpList[0]}"
                    x=$((x+1))
                done
            fi 

            # create and attach multus interfaces as requested
            n=0
            for subnetId in "${!subnetList[@]}";
            do
                secGrpId="${!secGrpList[n]}" 
                ### Get ipv6 cidr if any
                subnetipv6=`aws ec2 describe-subnets --subnet-ids ${!subnetId}\
                --query "Subnets[*].Ipv6CidrBlockAssociationSet[*].Ipv6CidrBlock" --output text`

                ### Create and attach interfaces, multus subnets and security groups are identified using tag Name:Value, 
                ### checks if subnet has IPV6 if true provisioned ENI with IPv6 else only IPv4
                if [ -n "$subnetipv6" ]; then
                    multusId=$(aws ec2 create-network-interface --subnet-id ${!subnetId} \
                    --description "VRF$((n+1))" --groups ${!secGrpId} --ipv6-address-count 1 \
                    --tag-specifications "ResourceType="network-interface",\
                    Tags=[{Key="node.k8s.amazonaws.com/no_manage",Value="true"}]" | jq -r '.NetworkInterface.NetworkInterfaceId');
                else
                    multusId=$(aws ec2 create-network-interface --subnet-id ${!subnetId} \
                    --description "VRF$((n+1))" --groups ${!secGrpId} \
                    --tag-specifications "ResourceType="network-interface",\
                    Tags=[{Key="node.k8s.amazonaws.com/no_manage",Value="true"}]" | jq -r '.NetworkInterface.NetworkInterfaceId');
                fi

                ### Attach the multus interface to EC2 worker, adjust device-index incrementally for every new attachment
                attachmentResult=$(aws ec2 attach-network-interface --network-interface-id ${!multusId} \
                --instance-id `curl -s http://169.254.169.254/latest/meta-data/instance-id` \
                --output text --device-index $((n+1 )) )
                IFS=' ' read -ra attachmentId <<< $attachmentResult
                aws ec2 modify-network-interface-attribute --network-interface-id ${!multusId} --no-source-dest-check
                aws ec2 modify-network-interface-attribute --attachment "AttachmentId"=${!attachmentId},"DeleteOnTermination"="True" \
                --network-interface-id ${!multusId}
                n=$((n+1))
            done
            echo "net.ipv4.conf.default.rp_filter = 0" | tee -a /etc/sysctl.conf
            echo "net.ipv4.conf.all.rp_filter = 0" | tee -a /etc/sysctl.conf
            sudo sysctl -p
            ls /sys/class/net/ > /tmp/ethList;cat /tmp/ethList |while read line ; do sudo ifconfig $line up; done
            grep eth /tmp/ethList |while read line ; do echo "ifconfig $line up" >> /etc/rc.d/rc.local; done
            systemctl enable rc-local
            chmod +x /etc/rc.d/rc.local
            
            # For kubelet arg input
            cat << EOF > /etc/systemd/system/kubelet.service.d/90-kubelet-extra-args.conf
            [Service]
            Environment='USERDATA_EXTRA_ARGS=${KubeletExtraArguments}'
            EOF
             # this kubelet.service update is for the version below than EKS 1.24 (e.g. up to 1.23)
            # but still you can keep the line even if you use EKS 1.24 or higher
            sed -i 's/KUBELET_EXTRA_ARGS/KUBELET_EXTRA_ARGS $USERDATA_EXTRA_ARGS/' /etc/systemd/system/kubelet.service
            # this update is for the EKS 1.24 or higher.
            sed -i 's/KUBELET_EXTRA_ARGS/KUBELET_EXTRA_ARGS $USERDATA_EXTRA_ARGS/' /etc/eks/containerd/kubelet-containerd.service
            --==BOUNDARY==--
            
          - SubnetIds: !Join [ " ", !Ref MultusSubnets ]
            SecGrpIds: !Join [ " ", !Ref MultusSecurityGroupIds ]

Outputs:
  EksMngLaunchTemplate: 
    Description: EKS Multus Nodegroup Launch Template
    Value: !Ref EksMngLaunchTemplate
